import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./global.scss";
import { Header } from "@/components/shared/header";
import { Footer } from "@/components/shared/footer";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${lato.className}`}>
				<div className="wrapper">
					<Header />
					<main className="main">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
